// Generated by https://quicktype.io

import { EventModel } from "./event";

export interface UserModel {
    userId:    number;
    firstName: string;
    lastName:  string;
    userName:  string;
    bio:       string;
    imageId:   number;
    active:    boolean;
    image:     Image;
    events:    EventModel[];
}

export interface Event {
    eventId:     number;
    name:        string;
    description: string;
    imageId:     number;
    expired:     boolean;
    active:      boolean;
    image:       Image;
}

export interface Image {
    imageId: number;
    path:    string;
}
